<?php

/**
 * @file
 * Install, update, and uninstall functions for the ajax_comments module.
 */

/**
 * Implementaton of hook_install
 */
function ajax_comments_install() {
  db_query("UPDATE {system} SET weight = 5 WHERE name = 'ajax_comments'");
}

/**
 * Implementaton of hook_uninstall
 */
function ajax_comments_uninstall() {
  db_query("DELETE FROM {variable} WHERE name LIKE 'ajax_comments_%%'");
  db_query("DELETE FROM {system} WHERE name = 'ajax_comments'");
}
